# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        MainWindow.setMaximumSize(500, 300)
        MainWindow.setMinimumSize(500, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(24)
        self.LA = QtWidgets.QLabel(self.centralwidget)
        self.LA.setFont(font)
        self.LA.setText("a = ")
        self.LA.setGeometry(20, 30, 91, 51)

        self.LB = QtWidgets.QLabel(self.centralwidget)
        self.LB.setFont(font)
        self.LB.setText("b = ")
        self.LB.setGeometry(20, 80, 91, 51)

        self.LC = QtWidgets.QLabel(self.centralwidget)
        self.LC.setFont(font)
        self.LC.setText("c = ")
        self.LC.setGeometry(20, 140, 91, 51)

        self.LaE = QtWidgets.QLineEdit(self.centralwidget)
        self.LaE.setFont(font)
        self.LaE.setGeometry(90, 40, 113, 41)

        self.LbE = QtWidgets.QLineEdit(self.centralwidget)
        self.LbE.setFont(font)
        self.LbE.setGeometry(90, 90, 113, 41)

        self.LcE = QtWidgets.QLineEdit(self.centralwidget)
        self.LcE.setFont(font)
        self.LcE.setGeometry(90, 140, 113, 41)
        self.LcE.setReadOnly(True)

        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setFont(font)
        self.btn.setText("+")
        self.btn.setGeometry(260, 10, 191, 51)
        self.btn.clicked.connect(self.summa)

        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setFont(font)
        self.btn.setText("-")
        self.btn.setGeometry(260, 80, 191, 51)
        self.btn.clicked.connect(self.difference)

        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setFont(font)
        self.btn.setText("*")
        self.btn.setGeometry(260, 140, 191, 51)
        self.btn.clicked.connect(self.multiplication)

        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setFont(font)
        self.btn.setText("/")
        self.btn.setGeometry(260, 210, 191, 51)
        self.btn.clicked.connect(self.division)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def summa(self):
        a = int(self.LaE.text())
        b = int(self.LbE.text())
        c = a + b
        self.LcE.setText(str(c))

    def difference(self):
        a = int(self.LaE.text())
        b = int(self.LbE.text())
        c = a - b
        self.LcE.setText(str(c))

    def multiplication(self):
        a = int(self.LaE.text())
        b = int(self.LbE.text())
        c = a * b
        self.LcE.setText(str(c))

    def division(self):
        a = int(self.LaE.text())
        b = int(self.LbE.text())
        c = a / b
        self.LcE.setText(str(c))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
